/** Machine-readable error codes. The app switches on these, never on message text. */
export const ERROR_CODES = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  OTP_NOT_FOUND: 'OTP_NOT_FOUND',
  OTP_RESEND_COOLDOWN: 'OTP_RESEND_COOLDOWN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  PROFILE_REQUIRED: 'PROFILE_REQUIRED',
  UNKNOWN_TASKS: 'UNKNOWN_TASKS',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  EMAIL_DELIVERY_FAILED: 'EMAIL_DELIVERY_FAILED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
